# CompileShaders.cmake
#
# Provides: volatile_compile_shader(SOURCE <file.comp> OUTPUT <stem>)
#
# For each shader:
#   1. Compiles <file.comp> -> ${CMAKE_CURRENT_BINARY_DIR}/shaders/<stem>.spv  (at build time)
#   2. Generates ${CMAKE_CURRENT_BINARY_DIR}/shaders/<stem>.c with a static C array
#      `static const uint8_t <stem>_spirv[];` and `static const size_t <stem>_spirv_size;`
#   3. Also generates a matching .h so consumers can do:
#        #include "generated/<stem>.h"
#        shader_from_embedded(<stem>_spirv, <stem>_spirv_size, SHADER_SPIRV);
#
# Requires glslc on PATH (or override via GLSLC_EXECUTABLE cache variable).

find_program(GLSLC_EXECUTABLE glslc DOC "Path to glslc SPIR-V compiler")

function(volatile_compile_shader)
  cmake_parse_arguments(ARG "" "SOURCE;OUTPUT;TARGET" "DEFINES" ${ARGN})

  if(NOT ARG_SOURCE)
    message(FATAL_ERROR "volatile_compile_shader: SOURCE required")
  endif()
  if(NOT ARG_OUTPUT)
    get_filename_component(ARG_OUTPUT ${ARG_SOURCE} NAME_WE)
  endif()
  if(NOT ARG_TARGET)
    set(ARG_TARGET "vulkan1.3")
  endif()

  get_filename_component(SOURCE_ABS ${ARG_SOURCE} ABSOLUTE)
  set(SPV_FILE   "${CMAKE_CURRENT_BINARY_DIR}/shaders/${ARG_OUTPUT}.spv")
  set(C_FILE     "${CMAKE_CURRENT_BINARY_DIR}/shaders/${ARG_OUTPUT}.c")
  set(H_FILE     "${CMAKE_CURRENT_BINARY_DIR}/shaders/${ARG_OUTPUT}.h")
  set(GEN_SCRIPT "${CMAKE_CURRENT_BINARY_DIR}/shaders/gen_${ARG_OUTPUT}.cmake")

  file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/shaders")

  # Build the glslc argument list
  set(_glslc_args
    --target-env=${ARG_TARGET}
    -fshader-stage=compute
  )
  foreach(_def IN LISTS ARG_DEFINES)
    list(APPEND _glslc_args "-D${_def}")
  endforeach()
  list(APPEND _glslc_args -o "${SPV_FILE}" "${SOURCE_ABS}")

  # Step 1: compile GLSL -> SPIR-V
  add_custom_command(
    OUTPUT  "${SPV_FILE}"
    COMMAND "${GLSLC_EXECUTABLE}" ${_glslc_args}
    DEPENDS "${SOURCE_ABS}"
    COMMENT "glslc ${ARG_SOURCE} -> ${ARG_OUTPUT}.spv"
    VERBATIM
  )

  # Step 2: generate C embed source.
  # We use a small CMake script so the binary->C conversion runs at build time.
  file(WRITE "${GEN_SCRIPT}" [=[
# Called by cmake -P at build time after SPV_FILE is produced.
cmake_minimum_required(VERSION 3.18)
set(SPV_FILE   "@SPV_FILE@")
set(C_FILE     "@C_FILE@")
set(H_FILE     "@H_FILE@")
set(STEM       "@ARG_OUTPUT@")

file(READ "${SPV_FILE}" _bytes HEX)
string(LENGTH "${_bytes}" _hex_len)
math(EXPR _byte_count "${_hex_len} / 2")

# Format as C hex literals, 16 per line
set(_c_bytes "")
math(EXPR _last "${_byte_count} - 1")
foreach(_i RANGE ${_last})
  math(EXPR _off "${_i} * 2")
  string(SUBSTRING "${_bytes}" ${_off} 2 _byte)
  if(_i LESS ${_last})
    string(APPEND _c_bytes "0x${_byte}, ")
  else()
    string(APPEND _c_bytes "0x${_byte}")
  endif()
  math(EXPR _col "(${_i} + 1) % 16")
  if(_col EQUAL 0 AND _i LESS ${_last})
    string(APPEND _c_bytes "\n  ")
  endif()
endforeach()

file(WRITE "${C_FILE}"
"/* Auto-generated by CompileShaders.cmake — do not edit */\n"
"#include \"${STEM}.h\"\n"
"\n"
"const uint8_t ${STEM}_spirv[] = {\n"
"  ${_c_bytes}\n"
"};\n"
"const size_t ${STEM}_spirv_size = ${_byte_count};\n"
)

file(WRITE "${H_FILE}"
"/* Auto-generated by CompileShaders.cmake — do not edit */\n"
"#pragma once\n"
"#include <stdint.h>\n"
"#include <stddef.h>\n"
"\n"
"/* SPIR-V bytecode for ${STEM} */\n"
"extern const uint8_t ${STEM}_spirv[];\n"
"extern const size_t  ${STEM}_spirv_size;\n"
)
]=])

  # Substitute actual values into the gen script
  configure_file("${GEN_SCRIPT}" "${GEN_SCRIPT}" @ONLY)

  add_custom_command(
    OUTPUT  "${C_FILE}" "${H_FILE}"
    COMMAND ${CMAKE_COMMAND} -P "${GEN_SCRIPT}"
    DEPENDS "${SPV_FILE}"
    COMMENT "Generating C embed for ${ARG_OUTPUT}.spv"
    VERBATIM
  )

  # Expose a target that other targets can depend on
  add_custom_target("shader_${ARG_OUTPUT}"
    DEPENDS "${SPV_FILE}" "${C_FILE}" "${H_FILE}"
  )

  # If GLSLC_EXECUTABLE is missing, issue a warning instead of hard error
  if(NOT GLSLC_EXECUTABLE)
    message(WARNING "volatile_compile_shader: glslc not found; shader '${ARG_OUTPUT}' will not be compiled at build time")
  endif()

  # Export the generated files for parent scope
  set(SHADER_${ARG_OUTPUT}_SPV  "${SPV_FILE}"  PARENT_SCOPE)
  set(SHADER_${ARG_OUTPUT}_C    "${C_FILE}"    PARENT_SCOPE)
  set(SHADER_${ARG_OUTPUT}_H    "${H_FILE}"    PARENT_SCOPE)
endfunction()
